/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory.app;

import java.awt.Color;
import java.io.InputStream;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Pads
 */
public class FrmOutStock extends javax.swing.JFrame {

    /**
     * Creates new form FrmOutStock
     */
    public FrmOutStock() {
        initComponents();
         if(SQLiteOutStock.openDB()){
             
            String[] columnsOutStock = {"OutStockID","BrandID", "BrandName","Category","Description","Quantity","Date","Remarks"};
            String[][] recordsOutStock= SQLite.executeDQL("OutStock", columnsOutStock,"1=1");
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(recordsOutStock, columnsOutStock);
            UIC.Table.setModel(tblOutStock, recordsOutStock, columnsOutStock); 
            SQLiteOutStock.closeDB();
         
    }
         
        
         
          this.setLocationRelativeTo(null);
          this.getContentPane().setBackground(Color.black);
          javax.swing.JTable table = tblOutStock;
        table.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent event) {
                if (table.getSelectedRow() > -1) {
                    // print first column value from selected row
                    
       
                    
                  
                   
                }
            }
        }); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutStock = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BxSort = new javax.swing.JComboBox<>();
        btnPrintOS = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menAdd = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tblOutStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OutStockID", "BrandID", "BrandName", "Category", "Description", "Quantity", "Date", "Remarks"
            }
        ));
        jScrollPane1.setViewportView(tblOutStock);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("OUT STOCK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("SEARCH");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("SORT BY");

        BxSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BrandID", "BrandName", "Category", "Quantity", "Date", "Remarks" }));
        BxSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxSortActionPerformed(evt);
            }
        });

        btnPrintOS.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnPrintOS.setForeground(new java.awt.Color(255, 51, 51));
        btnPrintOS.setText("PRINT OUT STOCK");
        btnPrintOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintOSActionPerformed(evt);
            }
        });

        jMenu1.setText("Option");

        menAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menAdd.setText("Add Released Product");
        menAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAddActionPerformed(evt);
            }
        });
        jMenu1.add(menAdd);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Main");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(BxSort, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrintOS)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BxSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintOS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FrmMain().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAddActionPerformed
        new FrmOSAdd().setVisible(true);
//        dispose();
    }//GEN-LAST:event_menAddActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try{
  
            SQLiteOutStock.conn = getConnection(SQLiteOutStock.url);
            SQLiteOutStock.stmt = SQLiteOutStock.conn.createStatement();
            String searched = txtSearch.getText();
            if(txtSearch.equals("")){
                        
             if(SQLiteOutStock.openDB()){
            String[][] records = SQLiteOutStock.read("OutStock");
            String[] columns = {"OutStockID","BrandID","BrandName","Category","Description","Quantity","Date","Remarks"};
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(records, columns);
            this.tblOutStock.setModel(model);
            SQLiteOutStock.closeDB();
        }
            }
            else{
                String query = "SELECT * FROM OutStock"
                        + " where BrandID like '%" + searched + "%'"
                        + " or BrandName like '%" + searched + "%'";
                ResultSet rs = SQLiteOutStock.stmt.executeQuery(query);
                this.tblOutStock.setModel(DbUtils.resultSetToTableModel(rs));
            }
            SQLiteOutStock.conn.close();
        }
        catch(Exception e){
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void BxSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxSortActionPerformed
        if(SQLiteOutStock.openDB()){
            String[][] data = SQLiteOutStock.sortA("OutStock","BrandID");
            String[] column = {"OutStockID","BrandID","BrandName","Category","Description","Quantity","Date","Remarks"};
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, column);
            this.tblOutStock.setModel(model);
            SQLiteOutStock.closeDB();
        }
        if(SQLiteOutStock.openDB()){
            String[][] data = SQLiteOutStock.sortA("OutStock","BrandName");
            String[] column = {"OutStockID","BrandID","BrandName","Category","Description","Quantity","Date","Remarks"};
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, column);
            this.tblOutStock.setModel(model);
            SQLiteOutStock.closeDB();
        }
    }//GEN-LAST:event_BxSortActionPerformed

    private void btnPrintOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintOSActionPerformed
        try{
            if(SQLite.openDB()){
                String InStockReport = ("OutStockReport.jrxml");
                InputStream file = getClass().getResourceAsStream(InStockReport);
                UIC.Report.viewReport2(file);
                //UIC.Report.viewReport(jspReport, reportName);
                SQLite.closeDB();
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }        
    }//GEN-LAST:event_btnPrintOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOutStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOutStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOutStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOutStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOutStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BxSort;
    private javax.swing.JButton btnPrintOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menAdd;
    private javax.swing.JTable tblOutStock;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
